language: scala

sudo: false

scala:
  - 2.12.4

jdk:
  - oraclejdk8

before_install:
  - export MILL_VERSION=0.1.1
  - if [ ! -d $HOME/.bin ]; then mkdir $HOME/.bin; fi
  # Update mill only if the desired version isn't cached
  - if [ ! -f $HOME/.bin/mill-$MILL_VERSION ]; then
        curl -L -o $HOME/.bin/mill-$MILL_VERSION https://github.com/lihaoyi/mill/releases/download/$MILL_VERSION/$MILL_VERSION
        chmod +x $HOME/.bin/mill-$MILL_VERSION
        if [ -L $HOME/.bin/mill ]; then unlink $HOME/.bin/mill; fi
        ln -s $HOME/.bin/mill-$MILL_VERSION $HOME/.bin/mill
    fi
  - export PATH=$HOME/.bin:$PATH

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier
  - $HOME/.bin

matrix:
  include:
  - env: SCALA_VERSION=2.11.12
  - env: SCALA_VERSION=2.12.4

script:
  - mill cassie[$SCALA_VERSION].test

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  # See https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html#Caching
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete